language: cpp

matrix:
  include:
    - name: "linux_x64"
      os: linux
      sudo: required
      env: 
        - DOCKER_IMAGE=pmeira/manylinux_wheel_cmake_fpc320
        - KLUSOLVEX_URL=https://github.com/dss-extensions/klusolve/releases/download/1.0.0a1/klusolvex_1.0.0a1_linux_x64.tar.gz
      services:
        - docker
      install:
        - docker pull $DOCKER_IMAGE
      script: 
        - wget "${KLUSOLVEX_URL}" -Oklusolvex.tar.gz -q
        - tar zxf klusolvex.tar.gz
        - cp -r klusolvex/lib/* ./lib/
        - docker run --rm -v `pwd`/..:/io -e TRAVIS_TAG="${TRAVIS_TAG}" $DOCKER_IMAGE bash /io/dss_capi/ci/build_linux_x64.sh
        - ls -lR lib
        
    - name: "linux_x86"
      os: linux
      sudo: required
      env: 
        - DOCKER_IMAGE=pmeira/manylinux_wheel_cmake_fpc320_i686
        - KLUSOLVEX_URL=https://github.com/dss-extensions/klusolve/releases/download/1.0.0a1/klusolvex_1.0.0a1_linux_x86.tar.gz
      services:
        - docker
      install:
        - docker pull $DOCKER_IMAGE
      script: 
        - wget "${KLUSOLVEX_URL}" -Oklusolvex.tar.gz -q
        - tar zxf klusolvex.tar.gz
        - cp -r klusolvex/lib/* ./lib/
        - docker run --rm -v `pwd`/..:/io -e TRAVIS_TAG="${TRAVIS_TAG}" $DOCKER_IMAGE bash /io/dss_capi/ci/build_linux_x86.sh
        - ls -lR lib
        
    - name: "osx_x64"
      os: osx
      env:
        - KLUSOLVEX_URL=https://github.com/dss-extensions/klusolve/releases/download/1.0.0a1/klusolvex_1.0.0a1_darwin_x64.tar.gz
      before_install:
        - |
          wget https://sourceforge.net/projects/freepascal/files/Mac%20OS%20X/3.2.0/fpc-3.2.0.intel-macosx.dmg/download -Ofpc.dmg -q
          sudo hdiutil attach fpc.dmg
          sudo installer -package /Volumes/fpc-3.2.0.intel-macosx/fpc-3.2.0-intel-macosx.pkg -target /
      install: true
      script: 
        - wget "${KLUSOLVEX_URL}" -Oklusolvex.tar.gz -q
        - tar zxf klusolvex.tar.gz
        - cp -r klusolvex/lib/* ./lib/
        - bash make_metadata.sh
        - bash build_macos_x64.sh
        - ls -lR lib

deploy:
    provider: releases
    api_key:
        secure: EdLk19gG9FW/lhutyOI7EwMpSHBjUJTpk/mriX0CzgthzTbxThm+V/VzqIH5CTnVhbe7yqczvD006aAb2Yivhp+Ic9jSths49kLV2OXW1cf4SBf7nJkiGAJvyrGgq9VmTdtB1YP21dvWOKUHaVyZo3A5W7l4sas6OGtFDa6kNpfBGvBj7kDJv/aklqJq7AsJUlT7oyhzYawlZGBxQzBwgNdd0LHjTBlR9PgrCAb7pEkTko/ZMBwIq4wBFEBcF8YsdFt33EOog+HtXEy91kSJhCJi137b/AilWRHlOE0KnSnVRDW42cr1eRwIN7o5q935z/bpZPSq4qAgQkCojI5awOTBcpdOTTs6rUjIMv8d++PHf/RCPDBeNGeZH2V7/RosmTZs+pyW9KtPAlX0E5jaasuahlsrEV4hrdUZNAKZ7HjqpbTrLwJtWBW/r2Xo8GvrJu7gAG1x1iP29ebNrVvAoYh8TwMwhEMFmxz51ckxxRzyUpmsQljDt7/Ge7p+tCNh1y3FEAHzk0l73qGX3tBEWylChmEAPtifMJ7B33oywlOnYr1wKpdELeO2ShsSvk5L5lfymYN+/v0yoWR2nLK8yYhttvfxWQlZ7azrbC4+obUbkaFd6tw4jYyyP+S08rkKIj6roUdf4KjK+C0AQMxPqGeYw/W7Xx0sHZCOpCyDl0w=
    file_glob: true
    file: release/*
    draft: true
    skip_cleanup: true
    on:
        repo: dss-extensions/dss_capi
        tags: true
