image: Visual Studio 2017
clone_folder: c:\dss_capi
build_script:
- cmd: >-
    git clone https://github.com/PMeira/electricdss-src.git c:\electricdss-src

    "c:\Program Files\Git\bin\bash" -c "bash ./make_metadata.sh"

    appveyor downloadfile https://sourceforge.net/projects/dss-capi/files/FPC/FPC-win32-win64-3.0.4.7z/download -FileName FPC-win32-win64-3.0.4.7z

    7z x -oC:\ FPC-win32-win64-3.0.4.7z

    set PATH=%PATH%;C:\FPC\3.0.4\bin\i386-win32

    set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin

    mkdir c:\dss_capi\klusolve\build

    cd c:\dss_capi\klusolve\build

    cmake .. -DUSE_SYSTEM_SUITESPARSE=OFF -G"Visual Studio 15 2017 Win64"

    cmake --build . --config Release

    cd c:\dss_capi

    call build_win_x64.bat

    call build_win_x86.bat
    
deploy:
- provider: GitHub
  auth_token:
    secure: L6m26mQzEqO+j2OyLZGzerFWTQAwHyO2S9dKC2SRMwJkqQo8PazeZpXj/kkWsHK+
  artifact: /.*\.zip/
  draft: true
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
    